package com.github.caldav4j;

public interface TestConstants {

	String UID_TO_HREF_CACHE = "uidToHrefCache";
	String HREF_TO_RESOURCE_CACHE = "hrefToResourceCache";

	String CALDAV_SERVER_BAD_USERNAME = "IDONTEXIST";
	String CALENDAR_DESCRIPTION = "My sample calendar description";

	String ICS_RESOURCE_PATH = "icalendar/";
	
	// google caldav server requires event file name == UID
	String ICS_GOOGLE_DAILY_NY_5PM_UID = "DE916949-731D-4DAE-BA93-48A38B2B2030";
	String ICS_GOOGLE_DAILY_NY_5PM = ICS_GOOGLE_DAILY_NY_5PM_UID + ".ics";
	String ICS_GOOGLE_DAILY_NY_5PM_PATH = ICS_RESOURCE_PATH + "Google_Daily_NY_5pm.ics";
	String ICS_GOOGLE_DAILY_NY_5PM_SUMMARY = "Google_Daily_NY_5pm.";

	String ICS_GOOGLE_ALL_DAY_JAN1_UID = "C68DADAD-37CE-44F7-8A37-52E1D02E29CA";
	String ICS_GOOGLE_ALL_DAY_JAN1 = ICS_GOOGLE_ALL_DAY_JAN1_UID + ".ics";
	String ICS_GOOGLE_ALL_DAY_JAN1_PATH = ICS_RESOURCE_PATH + "Google_All_Day_NY_JAN1.ics";

	String ICS_GOOGLE_NORMAL_PACIFIC_1PM_UID = "0F94FE7B-8E01-4B27-835E-CD1431FD6475";
	String ICS_GOOGLE_NORMAL_PACIFIC_1PM = ICS_GOOGLE_NORMAL_PACIFIC_1PM_UID + ".ics";
	String ICS_GOOGLE_NORMAL_PACIFIC_1PM_PATH = ICS_RESOURCE_PATH + "Google_Normal_Pacific_1pm.ics";
	String ICS_GOOGLE_NORMAL_PACIFIC_1PM_SUMMARY = "Google_Normal_Pacific_8_1pm.";

	String ICS_GOOGLE_FLOATING_JAN2_7PM_UID = "0870D1E0-B17E-4875-85C5-2ABB02E27609";
	String ICS_GOOGLE_FLOATING_JAN2_7PM = ICS_GOOGLE_FLOATING_JAN2_7PM_UID + ".ics";
	String ICS_GOOGLE_FLOATING_JAN2_7PM_PATH = ICS_RESOURCE_PATH + "Google_Floating_Jan_2_7pm.ics";
	String ICS_GOOGLE_FLOATING_JAN2_7PM_SUMMARY = "Google_Floating_Jan_2_7pm.";

	String ICS_GOOGLE_SINGLE_EVENT_UID = "66be2585-327b-4cc1-93a7-d0e6de648183";
	String ICS_GOOGLE_SINGLE_EVENT = ICS_GOOGLE_SINGLE_EVENT_UID + ".ics";
	String ICS_GOOGLE_SINGLE_EVENT_PATH = ICS_RESOURCE_PATH + "Google_singleEvent.ics";

	String ICS_RECURRENT_TZ_UID = "0BDA85EC-7917-4D9A-93B7-FAE391CA7F51";
	String ICS_RECURRENT_TZ_PATH = ICS_RESOURCE_PATH + "Recurrent_with_timezone.ics";
	String ICS_RECURRENT_TZ_SUMMARY = "Recurrent_with_timezone";
	
	String ICS_DAY_VTODO_PATH = ICS_RESOURCE_PATH + "DAY-VTODO-123123.ics";
	
	String ICS_GOOGLE_NOUID_DAYLY_5PM_PATH = ICS_RESOURCE_PATH + "Google_NOUID_Daily_NY_5pm.ics";
}
